#################################################################################
#       USERS
#################################################################################
### get users
GET http://localhost:3000/api/users/all

### get by id
GET http://localhost:3000/api/users/8b567982-4b3e-44e0-b1f0-31bc0606a917

### post 
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "name":"Kevin Canaza",
    "email":"kevo@gmail.com",
    "username":"kevan",
    "age":22,
    "password":"kevocs",
    "gender":"OTRO"
}

### put
PUT http://localhost:3000/api/users/edit/513dbf2e-dc2b-4ae9-8985-c694b50d6d98
Content-Type: application/json

{    
    "boardsIds":["2baeb039-57e2-4778-9fd6-0e33c8681b3d"]
}

### delete
DELETE http://localhost:3000/api/users/delete/b0094288-ee41-40f5-b032-53cccb1ad1c6

#################################################################################
#       BOARDS
#################################################################################
GET http://localhost:3000/api/boards/all

### get by id
GET http://localhost:3000/api/boards/2baeb039-57e2-4778-9fd6-0e33c8681b3d

### post 
POST http://localhost:3000/api/boards/register
Content-Type: application/json

{
    "usersIds":["b0094288-ee41-40f5-b032-53cccb1ad1c6"],
    "title":"actividades de la semana",
    "description":"actividades y operaciones que realizar en la semana."
}

### put
PUT http://localhost:3000/api/boards/edit/17f633e6-e26c-4ae2-9549-a97dbba3ae07
Content-Type: application/json

{    
    "usersIds":["26cde860-d81c-4bff-ab1e-90746150bab6","5c222bcb-3a38-4444-b1e1-4b5055e21dc8"]
}

### delete
DELETE http://localhost:3000/api/boards/delete/fdcc7ba8-1925-4a0e-8d0a-0b1542545f28

#################################################################################
#       LISTS
#################################################################################
GET http://localhost:3000/api/lists/all

### get by id
GET http://localhost:3000/api/lists/e5e6cf7c-d4d9-443a-94c1-8aa553719e20

### post 
POST http://localhost:3000/api/lists/register
Content-Type: application/json

{
    "boardId": "d3c7352a-8e6e-4a9d-8ccd-8b1598b59c96",
    "title":"Lista del dia viernes",
    "description":"proyectos a realizar para este dia viernes."
}

### put
PUT http://localhost:3000/api/lists/edit/646d2327-1190-4f94-a35d-8fc8d894169a
Content-Type: application/json

{    
    "boardId":"8410744d-068e-4aeb-81d5-bf2a68fd7b88"
}

### delete
DELETE http://localhost:3000/api/lists/delete/d3c7352a-8e6e-4a9d-8ccd-8b1598b59c96

#################################################################################
#       TASK
#################################################################################
GET http://localhost:3000/api/tasks/all

### get by id
GET http://localhost:3000/api/tasks/99c9db65-8a83-49f1-8097-3acec26afb85

### post 
POST http://localhost:3000/api/tasks/register
Content-Type: application/json

{
    "listId": "e5e6cf7c-d4d9-443a-94c1-8aa553719e20",
    "title":"Creas aplicaciones web con nest.js",
    "description":"Desarrollo web de una api rest full para nest.js y postgres",
    "dueDate":"2023-12-13T01:27:45.978Z",
    "status":"NEW"
}

### put
PUT http://localhost:3000/api/tasks/edit/99c9db65-8a83-49f1-8097-3acec26afb85
Content-Type: application/json

{    
    "listId":"646d2327-1190-4f94-a35d-8fc8d894169a",
    "description":"desarollo con nestJs"
}

### delete
DELETE http://localhost:3000/api/tasks/delete/e6ef5f12-3306-4f12-8d39-207d17dd204b